# Generated by Django 6.0 on 2025-12-24 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalBlob',
            fields=[
                ('sha256_hash', models.CharField(help_text='SHA-256 hash of the file content', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(help_text='Actual file stored on local disk', upload_to='blobs/')),
                ('size', models.BigIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='drive.physicalblob')),
            ],
            options={
                'verbose_name': 'User File',
                'verbose_name_plural': 'User Files',
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
