# Generated by Django 6.0 on 2025-12-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereference',
            name='is_primary_uploader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='filename',
            field=models.CharField(max_length=1024),
        ),
    ]
